import 'package:flutter/material.dart';

import '../api/models.dart';
import '../copy.dart';
import '../model_manager.dart';
import '../theme.dart';
import 'app_card.dart';

/// Languages offered for medication-instruction translation at launch.
const _targetLanguages = <String>['Hindi', 'Spanish'];

/// On-device AI insights for one captured result: explain a flagged value,
/// draft doctor-visit questions, and (for prescriptions) translate the
/// instructions.
///
/// All text is generated by the on-device SLM through
/// [ModelManager.runInsightTask], which serialises calls behind the inference
/// queue and loads the model lazily. Nothing here interprets or flags values —
/// flags and panic detection come from `lab/clinical_engine.dart`, and this
/// card only explains what is already flagged.
class InsightCard extends StatefulWidget {
  const InsightCard({super.key, required this.models, required this.envelope});

  /// Null when the screen was opened without a model manager (e.g. a deep
  /// link); the card then explains that insights are unavailable.
  final ModelManager? models;

  final ResultEnvelope envelope;

  @override
  State<InsightCard> createState() => _InsightCardState();
}

class _InsightCardState extends State<InsightCard> {
  final Map<String, String> _explanations = {};
  final Map<String, String> _translations = {};
  String? _visitPrep;

  /// Key of the action currently running, so only that control shows a spinner.
  String? _busy;

  bool get _isPrescription => widget.envelope.kind == 'prescription';

  /// Most noteworthy tests first: panic values, then Stage 3 abnormal rows.
  List<LabTest> get _flaggedTests {
    final panic = widget.envelope.panicTests;
    final panicNames = panic.map((t) => t.testName).toSet();
    final abnormal = widget.envelope.abnormalTests
        .where((t) => !panicNames.contains(t.testName));
    return [...panic, ...abnormal];
  }

  String _instructions() {
    final lines = <String>[];
    for (final item in widget.envelope.prescriptionItems) {
      final parts = [item.medication, item.dosage, item.frequency]
          .where((v) => v != null && v.trim().isNotEmpty)
          .map((v) => v!.trim());
      if (parts.isNotEmpty) lines.add(parts.join(' '));
    }
    return lines.join('\n');
  }

  Future<String?> _run(String key, Future<String> Function() task) async {
    if (widget.models == null) return null;
    setState(() => _busy = key);
    try {
      final text = await task();
      if (mounted) setState(() => _busy = null);
      return text;
    } catch (e) {
      if (mounted) setState(() => _busy = null);
      _showError('Could not generate insight: $e');
      return null;
    }
  }

  Future<void> _explain(LabTest test) async {
    final key = test.testName;
    final text = await _run(
      'explain:$key',
      () => widget.models!.runInsightTask(
        (slm) => slm.explainBiomarker(
          testName: key,
          value: test.value == null ? '—' : formatNumber(test.value),
          unit: test.unit ?? '',
          direction: test.direction,
        ),
      ),
    );
    if (text == null || !mounted) return;
    setState(() {
      _explanations[key] = text.isEmpty
          ? 'No explanation was produced. Please try again.'
          : text;
    });
  }

  Future<void> _prepareQuestions() async {
    final flagged = _flaggedTests;
    if (flagged.isEmpty) {
      _showError(
        'No values are outside their printed reference range, so there is '
        'nothing to prepare questions about.',
      );
      return;
    }
    final payload = flagged
        .map(
          (t) => <String, dynamic>{
            'test_name': t.testName,
            'value': t.value == null ? '—' : formatNumber(t.value),
            'unit': t.unit ?? '',
            'direction': t.direction,
          },
        )
        .toList();
    final text = await _run(
      'visit-prep',
      () => widget.models!.runInsightTask(
        (slm) => slm.doctorVisitPrep(flaggedTests: payload),
      ),
    );
    if (text == null || !mounted) return;
    setState(() {
      _visitPrep =
          text.isEmpty ? 'No questions were produced. Please try again.' : text;
    });
  }

  Future<void> _translate(String language) async {
    final instructions = _instructions();
    if (instructions.isEmpty) {
      _showError('No medication instructions found to translate.');
      return;
    }
    final text = await _run(
      'translate:$language',
      () => widget.models!.runInsightTask(
        (slm) => slm.translateInstructions(
          instructions: instructions,
          targetLanguage: language,
        ),
      ),
    );
    if (text == null || !mounted) return;
    setState(() {
      _translations[language] =
          text.isEmpty ? 'No translation was produced. Please try again.' : text;
    });
  }

  void _showError(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(
      context,
    ).showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final flagged = _flaggedTests;
    final hasPrescription = _isPrescription &&
        widget.envelope.prescriptionItems.isNotEmpty;
    final applicable = flagged.isNotEmpty || hasPrescription;

    return AppCard(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              const Icon(Icons.auto_awesome_outlined, size: 18),
              const SizedBox(width: 8),
              Text('AI Insights', style: theme.textTheme.titleSmall),
            ],
          ),
          const SizedBox(height: 6),
          Text(insightsCaption, style: theme.textTheme.bodySmall),
          const SizedBox(height: 12),
          if (widget.models == null)
            Text(
              'Insights are unavailable in this context.',
              style: theme.textTheme.bodySmall,
            )
          else if (!applicable)
            Text(
              'No flagged values or instructions were found to explain.',
              style: theme.textTheme.bodySmall,
            )
          else ...[
            if (flagged.isNotEmpty) ...[
              Text(
                'Explain a flagged value',
                style: theme.textTheme.labelLarge,
              ),
              const SizedBox(height: 8),
              for (final test in flagged)
                _InsightRow(
                  label:
                      '${test.testName} · '
                      '${test.value == null ? '—' : formatNumber(test.value)} '
                      '${test.unit ?? ''}'.trim(),
                  busy: _busy == 'explain:${test.testName}',
                  actionLabel: 'Explain',
                  onAction: () => _explain(test),
                  result: _explanations[test.testName],
                ),
              const SizedBox(height: 12),
              FilledButton.icon(
                onPressed: _busy == null ? _prepareQuestions : null,
                icon: _busy == 'visit-prep'
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      )
                    : const Icon(Icons.medical_services_outlined, size: 20),
                label: const Text('Prepare 3 doctor questions'),
              ),
              if (_visitPrep != null) ...[
                const SizedBox(height: 12),
                SelectableText(_visitPrep!, style: theme.textTheme.bodyMedium),
              ],
            ],
            if (hasPrescription) ...[
              if (flagged.isNotEmpty) const SizedBox(height: 16),
              Text(
                'Translate instructions',
                style: theme.textTheme.labelLarge,
              ),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                children: [
                  for (final language in _targetLanguages)
                    OutlinedButton(
                      onPressed: _busy == null
                          ? () => _translate(language)
                          : null,
                      child: _busy == 'translate:$language'
                          ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : Text(language),
                    ),
                ],
              ),
              for (final entry in _translations.entries) ...[
                const SizedBox(height: 12),
                Text(entry.key, style: theme.textTheme.labelMedium),
                const SizedBox(height: 4),
                SelectableText(
                  entry.value,
                  style: theme.textTheme.bodyMedium,
                ),
              ],
            ],
            const SizedBox(height: 12),
            Text(
              insightDisclaimer,
              style: theme.textTheme.bodySmall?.copyWith(
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

class _InsightRow extends StatelessWidget {
  const _InsightRow({
    required this.label,
    required this.busy,
    required this.actionLabel,
    required this.onAction,
    required this.result,
  });

  final String label;
  final bool busy;
  final String actionLabel;
  final VoidCallback onAction;
  final String? result;

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(label, style: theme.textTheme.bodyMedium),
              ),
              TextButton(
                onPressed: busy ? null : onAction,
                child: busy
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : Text(actionLabel),
              ),
            ],
          ),
          if (result != null)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: AppColors.surfaceAlt(theme.brightness),
                borderRadius: BorderRadius.circular(AppRadius.control),
              ),
              child: SelectableText(
                result!,
                style: theme.textTheme.bodySmall,
              ),
            ),
        ],
      ),
    );
  }
}
